config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, except: [:destroy, :update, :edit] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "/lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "lists/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_banner-show.html.erb
<div class="banner", style="background-image: url('<%= cl_image_path @list.photo.key %>')">
  <div class="container">
    <h1 class="text-center"><%= @list.name.upcase %></h1>
  </div>
</div>

app/views/lists/_banner.html.erb
<div class="banner">
  <div class="container">
    <h1 class="text-center">Save any kind of movies</h1>
  </div>
</div>

app/views/lists/_cards.html.erb
<div class="container">
  <div class="row">
    <div class="cards">
      <% @lists.each do |list| %>
        <%= link_to list.name, list_path(list), class:"card-category col-12 text-decoration-none",
            style:"background-image: url('#{cl_image_path list.photo.key}')" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/lists">
    <%= image_tag "logo.png", alt: "Pop corns", width: 500 %>
  </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My lists", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "New list", new_list_path(@list), class: "btn btn-outline-primary" %>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<%= render "banner" %>
<div class="container">
  <div class="row align-items-center my-4">
    <div class="col-6">
      <h1>My lists</h1>
    </div>
    <div class="col-6 text-end">
      <%= link_to "Create a movie list", new_list_path(@list), class:"btn btn-success text-white" %>
    </div>
  </div>
</div>

<%= render "cards" %>

app/views/lists/new.html.erb
<div class="container">
  <div class="row justify-ccontent-center p-5 m-5 bg-white">
    <div class="col">
      <h1>New list</h1>
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= render "lists/banner-show" %>
<div class="container">
  <div class="row justify-content-conter my-5">
    <% @list.bookmarks.each do |bookmark| %>
    <div class="col-4 my-4">
      <div class="card shadow" style="width: 24rem;">
        <%= image_tag bookmark.movie.poster_url, alt: "Movie poster", class: "card-img-top" %>
        <div class="card-body">
          <p class="card-title"><strong><%= bookmark.movie.title %></strong> | <%= bookmark.movie.rating %> <i
              class="fa-solid fa-star text-warning"></i></p>
          <p class="card-text"><%= bookmark.movie.overview %></p>
        </div>
        <div class="card-footer">
          <p class="card-text"><%= bookmark.comment %></p>
          <%= link_to "Delete",  bookmark_path(bookmark), class: "btn btn-outline-danger",
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col bg-white p-5 my-5">
      <h2>Add a bookmark</h2>
      <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie, prompt: "Choose a movie" %>
      <%= f.input :comment, placeholder: "ex: Best movie I've ever see" %>
      <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col bg-white p-5 m-5">
      <h2>Review</h2>
    </div>
  </div>
</div>